### ISSUE TITLE
关于数据保存持久化

### ISSUE THREAD

**Issue by everhopingandwaiting** [Jinjiang/h5slides#15]
昨天用了一下， 发现功能很赞，
就是在数据存储这一块有点问题，  如果存储在 localStorge 中的话，只能在自己的机器上访问， 而且万一不小心，清空浏览器数据，那 做成的东西就白费了， 加之在手机上试了下 关闭浏览器后再打开，数据不会怎么保存，这可能是手机浏览器默认策略。

**Comment by everhopingandwaiting** [comment]
关于  js  本地文件操作 看了下，只有 IE 提供，不过 可以想 其他 方案

**Comment by everhopingandwaiting** [comment]
```
    function readData() {
        var data;
        var dataStr = storage.getItem('h5slides-data');
        if (dataStr) {
            data = JSON.parse(dataStr);
        }
        console.log('read');
        try {
        var isFileSaverSupported = !!new Blob;
        alert(dataStr);
        var blob = new Blob( [dataStr] , {type: "text/plain;charset=utf-8"});
        saveAs(blob, "hello world.txt");
    } catch (e) {
      alert("no");
    }
        return data;
    }
```

`<script src="js/FileSaver.js"></script>`

**Comment by Jinjiang** [comment]
目前只有localStorage是支持最广泛的存储规范，如果有更大的应用场景，可以考虑架个服务器，然后跟这个localStorage的接口对接一下，不过这个超出开源项目的范围了

**Comment by everhopingandwaiting** [comment]
就是 我现在的 感觉不很方便的一点 就是， 做的 东西只能 在本地 ，没办法，分享出去，我早上 说的 方法是 把 那些数据 通过 HTML5 的 File API 方法，保存成本地文件，这样就 有了 分享的渠道了。
谢谢你的 回复

**Comment by Maples7** [comment]
+1
