### ISSUE TITLE
是否考虑集成impress.js的功能

### ISSUE THREAD

**Issue by newsky** [Jinjiang/h5slides#9]
impress.js本身实现了slide的部分功能，是否考虑集成进来

**Comment by ncuzp** [comment]
我看过impress.js的代码之后也产生了这样的想法，就是impress.js是给那些懂代码的人用的，因此我也更希望有一个能通过界面操作就可以完成幻灯片制作的类似插件，但是H5Slides是否缺少类似保存的功能，后续是否能做到对制作好的幻灯片进行保存呢@Jinjiang

**Comment by Jinjiang** [comment]
目前W3C并没有一个本地存储的规范，现在IE有.mht文件格式，Safari有.webarchive文件格式，但都是私有协议，我目前一直处在观望状态 (不过最近多了一些思路，可以重新考虑一下) 这个issue我先关掉了
